package com.leo.common.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.leo.common.db.TestStudent;

import com.leo.common.db.TestStudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testStudentDaoConfig;

    private final TestStudentDao testStudentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testStudentDaoConfig = daoConfigMap.get(TestStudentDao.class).clone();
        testStudentDaoConfig.initIdentityScope(type);

        testStudentDao = new TestStudentDao(testStudentDaoConfig, this);

        registerDao(TestStudent.class, testStudentDao);
    }
    
    public void clear() {
        testStudentDaoConfig.clearIdentityScope();
    }

    public TestStudentDao getTestStudentDao() {
        return testStudentDao;
    }

}
